---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yaml"

- name: Install apache
  package:
    name: httpd
    state: present
  become: true

- name: Ensure httpd is started
  service:
    name: httpd
    state: started
    enabled: true
  become: true
